// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/pgc/gateway/player/v2/playurl.proto" (package "bilibili.pgc.gateway.player.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Wire-compatible subset used to remove PGC prompts and casting restrictions.
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PromptBar
 */
export interface PromptBar {
}
/**
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.ViewInfo
 */
export interface ViewInfo {
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.PromptBar try_watch_prompt_bar = 8
     */
    tryWatchPromptBar?: PromptBar;
}
/**
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.CastTips
 */
export interface CastTips {
    /**
     * @generated from protobuf field: int32 code = 1
     */
    code: number;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PlayAbilityExtConf
 */
export interface PlayAbilityExtConf {
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.CastTips cast_tips = 3
     */
    castTips?: CastTips;
}
/**
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PlayViewReply
 */
export interface PlayViewReply {
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ViewInfo view_info = 5
     */
    viewInfo?: ViewInfo;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.PlayAbilityExtConf play_ext_conf = 6
     */
    playExtConf?: PlayAbilityExtConf;
}
declare class PromptBar$Type extends MessageType<PromptBar> {
    constructor();
    create(value?: PartialMessage<PromptBar>): PromptBar;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PromptBar): PromptBar;
    internalBinaryWrite(message: PromptBar, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PromptBar
 */
export declare const PromptBar: PromptBar$Type;
declare class ViewInfo$Type extends MessageType<ViewInfo> {
    constructor();
    create(value?: PartialMessage<ViewInfo>): ViewInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewInfo): ViewInfo;
    internalBinaryWrite(message: ViewInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.ViewInfo
 */
export declare const ViewInfo: ViewInfo$Type;
declare class CastTips$Type extends MessageType<CastTips> {
    constructor();
    create(value?: PartialMessage<CastTips>): CastTips;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CastTips): CastTips;
    internalBinaryWrite(message: CastTips, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.CastTips
 */
export declare const CastTips: CastTips$Type;
declare class PlayAbilityExtConf$Type extends MessageType<PlayAbilityExtConf> {
    constructor();
    create(value?: PartialMessage<PlayAbilityExtConf>): PlayAbilityExtConf;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayAbilityExtConf): PlayAbilityExtConf;
    internalBinaryWrite(message: PlayAbilityExtConf, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PlayAbilityExtConf
 */
export declare const PlayAbilityExtConf: PlayAbilityExtConf$Type;
declare class PlayViewReply$Type extends MessageType<PlayViewReply> {
    constructor();
    create(value?: PartialMessage<PlayViewReply>): PlayViewReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayViewReply): PlayViewReply;
    internalBinaryWrite(message: PlayViewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PlayViewReply
 */
export declare const PlayViewReply: PlayViewReply$Type;
export {};
