// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/polymer/app/search/v1/search.proto" (package "bilibili.polymer.app.search.v1", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/polymer/app/search/v1/search.proto" (package "bilibili.polymer.app.search.v1", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class SearchGameCard$Type extends MessageType {
    constructor() {
        super("bilibili.polymer.app.search.v1.SearchGameCard", []);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.SearchGameCard
 */
export const SearchGameCard = new SearchGameCard$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchAdCard$Type extends MessageType {
    constructor() {
        super("bilibili.polymer.app.search.v1.SearchAdCard", []);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.SearchAdCard
 */
export const SearchAdCard = new SearchAdCard$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Item$Type extends MessageType {
    constructor() {
        super("bilibili.polymer.app.search.v1.Item", [
            { no: 1, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "trackid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "game", kind: "message", oneof: "cardItem", T: () => SearchGameCard },
            { no: 25, name: "cm", kind: "message", oneof: "cardItem", T: () => SearchAdCard }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.uri = "";
        message.trackid = "";
        message.cardItem = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uri */ 1:
                    message.uri = reader.string();
                    break;
                case /* string trackid */ 6:
                    message.trackid = reader.string();
                    break;
                case /* bilibili.polymer.app.search.v1.SearchGameCard game */ 11:
                    message.cardItem = {
                        oneofKind: "game",
                        game: SearchGameCard.internalBinaryRead(reader, reader.uint32(), options, message.cardItem.game)
                    };
                    break;
                case /* bilibili.polymer.app.search.v1.SearchAdCard cm */ 25:
                    message.cardItem = {
                        oneofKind: "cm",
                        cm: SearchAdCard.internalBinaryRead(reader, reader.uint32(), options, message.cardItem.cm)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string uri = 1; */
        if (message.uri !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uri);
        /* string trackid = 6; */
        if (message.trackid !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.trackid);
        /* bilibili.polymer.app.search.v1.SearchGameCard game = 11; */
        if (message.cardItem.oneofKind === "game")
            SearchGameCard.internalBinaryWrite(message.cardItem.game, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.polymer.app.search.v1.SearchAdCard cm = 25; */
        if (message.cardItem.oneofKind === "cm")
            SearchAdCard.internalBinaryWrite(message.cardItem.cm, writer.tag(25, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.Item
 */
export const Item = new Item$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchAllResponse$Type extends MessageType {
    constructor() {
        super("bilibili.polymer.app.search.v1.SearchAllResponse", [
            { no: 2, name: "trackid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "item", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Item }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.trackid = "";
        message.item = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string trackid */ 2:
                    message.trackid = reader.string();
                    break;
                case /* repeated bilibili.polymer.app.search.v1.Item item */ 4:
                    message.item.push(Item.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string trackid = 2; */
        if (message.trackid !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.trackid);
        /* repeated bilibili.polymer.app.search.v1.Item item = 4; */
        for (let i = 0; i < message.item.length; i++)
            Item.internalBinaryWrite(message.item[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.SearchAllResponse
 */
export const SearchAllResponse = new SearchAllResponse$Type();
