// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/polymer/app/search/v1/search.proto" (package "bilibili.polymer.app.search.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Wire-compatible subset used to identify search ads while preserving every
 * undeclared card and field as protobuf unknown data.
 *
 * @generated from protobuf message bilibili.polymer.app.search.v1.SearchGameCard
 */
export interface SearchGameCard {
}
/**
 * @generated from protobuf message bilibili.polymer.app.search.v1.SearchAdCard
 */
export interface SearchAdCard {
}
/**
 * @generated from protobuf message bilibili.polymer.app.search.v1.Item
 */
export interface Item {
    /**
     * @generated from protobuf field: string uri = 1
     */
    uri: string;
    /**
     * @generated from protobuf field: string trackid = 6
     */
    trackid: string;
    /**
     * @generated from protobuf oneof: card_item
     */
    cardItem: {
        oneofKind: "game";
        /**
         * @generated from protobuf field: bilibili.polymer.app.search.v1.SearchGameCard game = 11
         */
        game: SearchGameCard;
    } | {
        oneofKind: "cm";
        /**
         * @generated from protobuf field: bilibili.polymer.app.search.v1.SearchAdCard cm = 25
         */
        cm: SearchAdCard;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message bilibili.polymer.app.search.v1.SearchAllResponse
 */
export interface SearchAllResponse {
    /**
     * @generated from protobuf field: string trackid = 2
     */
    trackid: string;
    /**
     * @generated from protobuf field: repeated bilibili.polymer.app.search.v1.Item item = 4
     */
    item: Item[];
}
declare class SearchGameCard$Type extends MessageType<SearchGameCard> {
    constructor();
    create(value?: PartialMessage<SearchGameCard>): SearchGameCard;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchGameCard): SearchGameCard;
    internalBinaryWrite(message: SearchGameCard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.SearchGameCard
 */
export declare const SearchGameCard: SearchGameCard$Type;
declare class SearchAdCard$Type extends MessageType<SearchAdCard> {
    constructor();
    create(value?: PartialMessage<SearchAdCard>): SearchAdCard;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchAdCard): SearchAdCard;
    internalBinaryWrite(message: SearchAdCard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.SearchAdCard
 */
export declare const SearchAdCard: SearchAdCard$Type;
declare class Item$Type extends MessageType<Item> {
    constructor();
    create(value?: PartialMessage<Item>): Item;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Item): Item;
    internalBinaryWrite(message: Item, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.Item
 */
export declare const Item: Item$Type;
declare class SearchAllResponse$Type extends MessageType<SearchAllResponse> {
    constructor();
    create(value?: PartialMessage<SearchAllResponse>): SearchAllResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchAllResponse): SearchAllResponse;
    internalBinaryWrite(message: SearchAllResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.SearchAllResponse
 */
export declare const SearchAllResponse: SearchAllResponse$Type;
export {};
