// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/viewunite.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.UniteOpaqueMessage
 */
export interface UniteOpaqueMessage {
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.CardBasicInfo
 */
export interface CardBasicInfo {
    /**
     * @generated from protobuf field: string unique_id = 6
     */
    uniqueId: string;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.RelateCard
 */
export interface RelateCard {
    /**
     * @generated from protobuf field: int32 relate_card_type = 1
     */
    relateCardType: number;
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.UniteOpaqueMessage cm_stock = 11
     */
    cmStock?: UniteOpaqueMessage;
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.CardBasicInfo basic_info = 12
     */
    basicInfo?: CardBasicInfo;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.Relates
 */
export interface Relates {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.RelateCard cards = 1
     */
    cards: RelateCard[];
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.Module
 */
export interface Module {
    /**
     * @generated from protobuf field: int32 type = 1
     */
    type: number;
    /**
     * @generated from protobuf oneof: data
     */
    data: {
        oneofKind: "relates";
        /**
         * @generated from protobuf field: bilibili.app.viewunite.v1.Relates relates = 22
         */
        relates: Relates;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.IntroductionTab
 */
export interface IntroductionTab {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.Module modules = 2
     */
    modules: Module[];
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.TabModule
 */
export interface TabModule {
    /**
     * @generated from protobuf oneof: tab
     */
    tab: {
        oneofKind: "introduction";
        /**
         * @generated from protobuf field: bilibili.app.viewunite.v1.IntroductionTab introduction = 2
         */
        introduction: IntroductionTab;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.Tab
 */
export interface Tab {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.TabModule tab_module = 1
     */
    tabModule: TabModule[];
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.CM
 */
export interface CM {
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.RelatesFeedReply
 */
export interface RelatesFeedReply {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.RelateCard relates = 1
     */
    relates: RelateCard[];
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ViewReply
 */
export interface ViewReply {
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.Tab tab = 5
     */
    tab?: Tab;
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.CM cm = 7
     */
    cm?: CM;
}
declare class UniteOpaqueMessage$Type extends MessageType<UniteOpaqueMessage> {
    constructor();
    create(value?: PartialMessage<UniteOpaqueMessage>): UniteOpaqueMessage;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UniteOpaqueMessage): UniteOpaqueMessage;
    internalBinaryWrite(message: UniteOpaqueMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.UniteOpaqueMessage
 */
export declare const UniteOpaqueMessage: UniteOpaqueMessage$Type;
declare class CardBasicInfo$Type extends MessageType<CardBasicInfo> {
    constructor();
    create(value?: PartialMessage<CardBasicInfo>): CardBasicInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CardBasicInfo): CardBasicInfo;
    internalBinaryWrite(message: CardBasicInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.CardBasicInfo
 */
export declare const CardBasicInfo: CardBasicInfo$Type;
declare class RelateCard$Type extends MessageType<RelateCard> {
    constructor();
    create(value?: PartialMessage<RelateCard>): RelateCard;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RelateCard): RelateCard;
    internalBinaryWrite(message: RelateCard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.RelateCard
 */
export declare const RelateCard: RelateCard$Type;
declare class Relates$Type extends MessageType<Relates> {
    constructor();
    create(value?: PartialMessage<Relates>): Relates;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Relates): Relates;
    internalBinaryWrite(message: Relates, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.Relates
 */
export declare const Relates: Relates$Type;
declare class Module$Type extends MessageType<Module> {
    constructor();
    create(value?: PartialMessage<Module>): Module;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Module): Module;
    internalBinaryWrite(message: Module, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.Module
 */
export declare const Module: Module$Type;
declare class IntroductionTab$Type extends MessageType<IntroductionTab> {
    constructor();
    create(value?: PartialMessage<IntroductionTab>): IntroductionTab;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IntroductionTab): IntroductionTab;
    internalBinaryWrite(message: IntroductionTab, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.IntroductionTab
 */
export declare const IntroductionTab: IntroductionTab$Type;
declare class TabModule$Type extends MessageType<TabModule> {
    constructor();
    create(value?: PartialMessage<TabModule>): TabModule;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TabModule): TabModule;
    internalBinaryWrite(message: TabModule, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.TabModule
 */
export declare const TabModule: TabModule$Type;
declare class Tab$Type extends MessageType<Tab> {
    constructor();
    create(value?: PartialMessage<Tab>): Tab;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Tab): Tab;
    internalBinaryWrite(message: Tab, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.Tab
 */
export declare const Tab: Tab$Type;
declare class CM$Type extends MessageType<CM> {
    constructor();
    create(value?: PartialMessage<CM>): CM;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CM): CM;
    internalBinaryWrite(message: CM, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.CM
 */
export declare const CM: CM$Type;
declare class RelatesFeedReply$Type extends MessageType<RelatesFeedReply> {
    constructor();
    create(value?: PartialMessage<RelatesFeedReply>): RelatesFeedReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RelatesFeedReply): RelatesFeedReply;
    internalBinaryWrite(message: RelatesFeedReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.RelatesFeedReply
 */
export declare const RelatesFeedReply: RelatesFeedReply$Type;
declare class ViewReply$Type extends MessageType<ViewReply> {
    constructor();
    create(value?: PartialMessage<ViewReply>): ViewReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewReply): ViewReply;
    internalBinaryWrite(message: ViewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ViewReply
 */
export declare const ViewReply: ViewReply$Type;
export {};
