// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/viewprogress.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ProgressOpaqueMessage
 */
export interface ProgressOpaqueMessage {
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.VideoGuide
 */
export interface VideoGuide {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.ProgressOpaqueMessage material = 1
     */
    material: ProgressOpaqueMessage[];
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.ProgressOpaqueMessage video_point = 2
     */
    videoPoint?: ProgressOpaqueMessage;
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.ProgressOpaqueMessage contract_card = 3
     */
    contractCard?: ProgressOpaqueMessage;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ViewProgressReply
 */
export interface ViewProgressReply {
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.VideoGuide video_guide = 1
     */
    videoGuide?: VideoGuide;
}
declare class ProgressOpaqueMessage$Type extends MessageType<ProgressOpaqueMessage> {
    constructor();
    create(value?: PartialMessage<ProgressOpaqueMessage>): ProgressOpaqueMessage;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProgressOpaqueMessage): ProgressOpaqueMessage;
    internalBinaryWrite(message: ProgressOpaqueMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressOpaqueMessage
 */
export declare const ProgressOpaqueMessage: ProgressOpaqueMessage$Type;
declare class VideoGuide$Type extends MessageType<VideoGuide> {
    constructor();
    create(value?: PartialMessage<VideoGuide>): VideoGuide;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VideoGuide): VideoGuide;
    internalBinaryWrite(message: VideoGuide, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.VideoGuide
 */
export declare const VideoGuide: VideoGuide$Type;
declare class ViewProgressReply$Type extends MessageType<ViewProgressReply> {
    constructor();
    create(value?: PartialMessage<ViewProgressReply>): ViewProgressReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewProgressReply): ViewProgressReply;
    internalBinaryWrite(message: ViewProgressReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ViewProgressReply
 */
export declare const ViewProgressReply: ViewProgressReply$Type;
export {};
