// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/viewprogress.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ProgressMaterial
 */
export interface ProgressMaterial {
    /**
     * @generated from protobuf field: string text = 2
     */
    text: string;
    /**
     * @generated from protobuf field: string url = 3
     */
    url: string;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ProgressVideoPoint
 */
export interface ProgressVideoPoint {
    /**
     * @generated from protobuf field: bool point_permanent = 3
     */
    pointPermanent: boolean;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ProgressContractCard
 */
export interface ProgressContractCard {
    /**
     * @generated from protobuf field: bool play_display_switch = 12
     */
    playDisplaySwitch: boolean;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ProgressVideoShot
 */
export interface ProgressVideoShot {
    /**
     * @generated from protobuf field: string pv_data = 1
     */
    pvData: string;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.VideoGuide
 */
export interface VideoGuide {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.ProgressMaterial material = 1
     */
    material: ProgressMaterial[];
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.ProgressVideoPoint video_point = 2
     */
    videoPoint?: ProgressVideoPoint;
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.ProgressContractCard contract_card = 3
     */
    contractCard?: ProgressContractCard;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ViewProgressReply
 */
export interface ViewProgressReply {
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.VideoGuide video_guide = 1
     */
    videoGuide?: VideoGuide;
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.ProgressVideoShot arc_shot = 3
     */
    arcShot?: ProgressVideoShot;
}
declare class ProgressMaterial$Type extends MessageType<ProgressMaterial> {
    constructor();
    create(value?: PartialMessage<ProgressMaterial>): ProgressMaterial;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProgressMaterial): ProgressMaterial;
    internalBinaryWrite(message: ProgressMaterial, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressMaterial
 */
export declare const ProgressMaterial: ProgressMaterial$Type;
declare class ProgressVideoPoint$Type extends MessageType<ProgressVideoPoint> {
    constructor();
    create(value?: PartialMessage<ProgressVideoPoint>): ProgressVideoPoint;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProgressVideoPoint): ProgressVideoPoint;
    internalBinaryWrite(message: ProgressVideoPoint, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressVideoPoint
 */
export declare const ProgressVideoPoint: ProgressVideoPoint$Type;
declare class ProgressContractCard$Type extends MessageType<ProgressContractCard> {
    constructor();
    create(value?: PartialMessage<ProgressContractCard>): ProgressContractCard;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProgressContractCard): ProgressContractCard;
    internalBinaryWrite(message: ProgressContractCard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressContractCard
 */
export declare const ProgressContractCard: ProgressContractCard$Type;
declare class ProgressVideoShot$Type extends MessageType<ProgressVideoShot> {
    constructor();
    create(value?: PartialMessage<ProgressVideoShot>): ProgressVideoShot;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProgressVideoShot): ProgressVideoShot;
    internalBinaryWrite(message: ProgressVideoShot, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressVideoShot
 */
export declare const ProgressVideoShot: ProgressVideoShot$Type;
declare class VideoGuide$Type extends MessageType<VideoGuide> {
    constructor();
    create(value?: PartialMessage<VideoGuide>): VideoGuide;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VideoGuide): VideoGuide;
    internalBinaryWrite(message: VideoGuide, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.VideoGuide
 */
export declare const VideoGuide: VideoGuide$Type;
declare class ViewProgressReply$Type extends MessageType<ViewProgressReply> {
    constructor();
    create(value?: PartialMessage<ViewProgressReply>): ViewProgressReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewProgressReply): ViewProgressReply;
    internalBinaryWrite(message: ViewProgressReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ViewProgressReply
 */
export declare const ViewProgressReply: ViewProgressReply$Type;
export {};
