// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/viewprogress.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/viewprogress.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class ProgressOpaqueMessage$Type extends MessageType {
    constructor() {
        super("bilibili.app.viewunite.v1.ProgressOpaqueMessage", []);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressOpaqueMessage
 */
export const ProgressOpaqueMessage = new ProgressOpaqueMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VideoGuide$Type extends MessageType {
    constructor() {
        super("bilibili.app.viewunite.v1.VideoGuide", [
            { no: 1, name: "material", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProgressOpaqueMessage },
            { no: 2, name: "video_point", kind: "message", T: () => ProgressOpaqueMessage },
            { no: 3, name: "contract_card", kind: "message", T: () => ProgressOpaqueMessage }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.material = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bilibili.app.viewunite.v1.ProgressOpaqueMessage material */ 1:
                    message.material.push(ProgressOpaqueMessage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bilibili.app.viewunite.v1.ProgressOpaqueMessage video_point */ 2:
                    message.videoPoint = ProgressOpaqueMessage.internalBinaryRead(reader, reader.uint32(), options, message.videoPoint);
                    break;
                case /* bilibili.app.viewunite.v1.ProgressOpaqueMessage contract_card */ 3:
                    message.contractCard = ProgressOpaqueMessage.internalBinaryRead(reader, reader.uint32(), options, message.contractCard);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated bilibili.app.viewunite.v1.ProgressOpaqueMessage material = 1; */
        for (let i = 0; i < message.material.length; i++)
            ProgressOpaqueMessage.internalBinaryWrite(message.material[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.app.viewunite.v1.ProgressOpaqueMessage video_point = 2; */
        if (message.videoPoint)
            ProgressOpaqueMessage.internalBinaryWrite(message.videoPoint, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.app.viewunite.v1.ProgressOpaqueMessage contract_card = 3; */
        if (message.contractCard)
            ProgressOpaqueMessage.internalBinaryWrite(message.contractCard, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.VideoGuide
 */
export const VideoGuide = new VideoGuide$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewProgressReply$Type extends MessageType {
    constructor() {
        super("bilibili.app.viewunite.v1.ViewProgressReply", [
            { no: 1, name: "video_guide", kind: "message", T: () => VideoGuide }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.app.viewunite.v1.VideoGuide video_guide */ 1:
                    message.videoGuide = VideoGuide.internalBinaryRead(reader, reader.uint32(), options, message.videoGuide);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.app.viewunite.v1.VideoGuide video_guide = 1; */
        if (message.videoGuide)
            VideoGuide.internalBinaryWrite(message.videoGuide, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ViewProgressReply
 */
export const ViewProgressReply = new ViewProgressReply$Type();
