// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/viewprogress.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class ProgressMaterial$Type extends MessageType {
    constructor() {
        super("bilibili.app.viewunite.v1.ProgressMaterial", [
            { no: 2, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.text = "";
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string text */ 2:
                    message.text = reader.string();
                    break;
                case /* string url */ 3:
                    message.url = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string text = 2; */
        if (message.text !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.text);
        /* string url = 3; */
        if (message.url !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.url);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressMaterial
 */
export const ProgressMaterial = new ProgressMaterial$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProgressVideoPoint$Type extends MessageType {
    constructor() {
        super("bilibili.app.viewunite.v1.ProgressVideoPoint", [
            { no: 3, name: "point_permanent", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.pointPermanent = false;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool point_permanent */ 3:
                    message.pointPermanent = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bool point_permanent = 3; */
        if (message.pointPermanent !== false)
            writer.tag(3, WireType.Varint).bool(message.pointPermanent);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressVideoPoint
 */
export const ProgressVideoPoint = new ProgressVideoPoint$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProgressContractCard$Type extends MessageType {
    constructor() {
        super("bilibili.app.viewunite.v1.ProgressContractCard", [
            { no: 12, name: "play_display_switch", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.playDisplaySwitch = false;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool play_display_switch */ 12:
                    message.playDisplaySwitch = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bool play_display_switch = 12; */
        if (message.playDisplaySwitch !== false)
            writer.tag(12, WireType.Varint).bool(message.playDisplaySwitch);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressContractCard
 */
export const ProgressContractCard = new ProgressContractCard$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProgressVideoShot$Type extends MessageType {
    constructor() {
        super("bilibili.app.viewunite.v1.ProgressVideoShot", [
            { no: 1, name: "pv_data", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.pvData = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string pv_data */ 1:
                    message.pvData = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string pv_data = 1; */
        if (message.pvData !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.pvData);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ProgressVideoShot
 */
export const ProgressVideoShot = new ProgressVideoShot$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VideoGuide$Type extends MessageType {
    constructor() {
        super("bilibili.app.viewunite.v1.VideoGuide", [
            { no: 1, name: "material", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProgressMaterial },
            { no: 2, name: "video_point", kind: "message", T: () => ProgressVideoPoint },
            { no: 3, name: "contract_card", kind: "message", T: () => ProgressContractCard }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.material = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bilibili.app.viewunite.v1.ProgressMaterial material */ 1:
                    message.material.push(ProgressMaterial.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bilibili.app.viewunite.v1.ProgressVideoPoint video_point */ 2:
                    message.videoPoint = ProgressVideoPoint.internalBinaryRead(reader, reader.uint32(), options, message.videoPoint);
                    break;
                case /* bilibili.app.viewunite.v1.ProgressContractCard contract_card */ 3:
                    message.contractCard = ProgressContractCard.internalBinaryRead(reader, reader.uint32(), options, message.contractCard);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated bilibili.app.viewunite.v1.ProgressMaterial material = 1; */
        for (let i = 0; i < message.material.length; i++)
            ProgressMaterial.internalBinaryWrite(message.material[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.app.viewunite.v1.ProgressVideoPoint video_point = 2; */
        if (message.videoPoint)
            ProgressVideoPoint.internalBinaryWrite(message.videoPoint, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.app.viewunite.v1.ProgressContractCard contract_card = 3; */
        if (message.contractCard)
            ProgressContractCard.internalBinaryWrite(message.contractCard, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.VideoGuide
 */
export const VideoGuide = new VideoGuide$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewProgressReply$Type extends MessageType {
    constructor() {
        super("bilibili.app.viewunite.v1.ViewProgressReply", [
            { no: 1, name: "video_guide", kind: "message", T: () => VideoGuide },
            { no: 3, name: "arc_shot", kind: "message", T: () => ProgressVideoShot }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.app.viewunite.v1.VideoGuide video_guide */ 1:
                    message.videoGuide = VideoGuide.internalBinaryRead(reader, reader.uint32(), options, message.videoGuide);
                    break;
                case /* bilibili.app.viewunite.v1.ProgressVideoShot arc_shot */ 3:
                    message.arcShot = ProgressVideoShot.internalBinaryRead(reader, reader.uint32(), options, message.arcShot);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.app.viewunite.v1.VideoGuide video_guide = 1; */
        if (message.videoGuide)
            VideoGuide.internalBinaryWrite(message.videoGuide, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.app.viewunite.v1.ProgressVideoShot arc_shot = 3; */
        if (message.arcShot)
            ProgressVideoShot.internalBinaryWrite(message.arcShot, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ViewProgressReply
 */
export const ViewProgressReply = new ViewProgressReply$Type();
