import { defineConfig } from "@iringo/arguments-builder";

export default defineConfig({
	output: {
		surge: {
			path: "./dist/BiliBili.ADBlock.sgmodule",
			transformEgern: {
				enable: true,
				path: "./dist/BiliBili.ADBlock.yaml",
			},
		},
		loon: {
			path: "./dist/BiliBili.ADBlock.plugin",
		},
		customItems: [
			{
				path: "./dist/BiliBili.ADBlock.stoverride",
				template: "./template/stash.handlebars",
			},
			{
				path: "./dist/BiliBili.ADBlock.snippet",
				template: "./template/quantumultx.handlebars",
			},
		],
		dts: {
			isExported: true,
			path: "./src/types.d.ts",
		},
		boxjsSettings: {
			path: "./template/boxjs.settings.json",
			scope: "@BiliBili.ADBlock.Settings",
		},
	},
	args: [
		{
			key: "Splash",
			name: "[开屏] 去除广告",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Feed.AD",
			name: "[推荐] 去除广告",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Feed.Activity",
			name: "[推荐] 去除“活动大图”",
			defaultValue: false,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Feed.Vertical",
			name: "[推荐] 去除竖屏视频",
			defaultValue: false,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Feed.BlockUpLiveList",
			name: "[推荐] 屏蔽UP主直播推广",
			defaultValue: "",
			type: "string",
			description: "填写up主uid，以英文逗号隔开。",
		},
		{
			key: "Feed.Story",
			name: "[首页] 去除短视频流广告",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Feed.StoryCommercial",
			name: "[首页] 去除Story商业按钮",
			defaultValue: true,
			type: "boolean",
			description: "移除Story中的“助TA必火”等商业推广按钮，不删除视频卡片。",
		},
		{
			key: "Search.AD",
			name: "[搜索] 去除广告",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Search.Tracking",
			name: "[搜索] 移除响应跟踪参数",
			defaultValue: false,
			type: "boolean",
			description: "清理SearchAll结果对象及跳转链接中的trackid、report_flow_data，不修改播放签名和预加载数据。",
		},
		{
			key: "Search.HotSearch",
			name: "[搜索] 去除“热搜”",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "PGC.AD",
			name: "[番剧电影] 去除广告",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Xlive.AD",
			name: "[直播] 去除广告",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Xlive.RemoveTrackingCallbacks",
			name: "[直播] 移除推荐回调",
			defaultValue: false,
			type: "boolean",
			description: "移除直播推荐卡的show_callback与click_callback；可能影响推荐状态和翻页。",
		},
		{
			key: "Xlive.RemovePreloadTracking",
			name: "[直播] 移除预载链接trackid",
			defaultValue: false,
			type: "boolean",
			description: "只移除直播small_card_v1.subtitle_style.link中的trackid，保留播放、清晰度和会话参数。",
		},
		{
			key: "Dynamic.HotTopics",
			name: "[动态] 去除“热门话题”",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Dynamic.MostVisited",
			name: "[动态] 去除“最常访问”",
			defaultValue: false,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Dynamic.MostVisitedLiveOnly",
			name: "[动态] “最常访问”仅显示直播",
			defaultValue: false,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Dynamic.AdCard",
			name: "[动态] 去除广告卡片",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Dynamic.PersonalAdCard",
			name: "[动态] 去除个人流广告卡片",
			defaultValue: false,
			type: "boolean",
			description: "过滤DynAllPersonal与DynVideoPersonal中的cardType=15；当前抓包尚无广告阳性样本。",
		},
		{
			key: "View.AD",
			name: "[用户投稿] 去除视频广告",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "DM.Command",
			name: "[弹幕] 去除交互式弹幕",
			defaultValue: false,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "DM.Colorful",
			name: "[弹幕] 替换彩色弹幕",
			defaultValue: false,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "DM.Airborne",
			name: "[弹幕] 空降助手",
			defaultValue: false,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Reply.AD",
			name: "[评论] 去除广告",
			defaultValue: true,
			type: "boolean",
			description: "是否启用此处修改",
		},
		{
			key: "Reply.CommercialLinks",
			name: "[评论] 禁用普通评论商业跳转",
			defaultValue: false,
			type: "boolean",
			description: "保留普通评论正文与回复树，仅移除已识别商品链接的可点击映射。",
		},
		{
			key: "Reply.SubjectDescriptionCommercial",
			name: "[评论] 隐藏编辑器商品能力",
			defaultValue: false,
			type: "boolean",
			description: "移除SubjectDescription中的商品与商业助手按钮(type 5/8)；当前抓包中它们均为隐藏状态。",
		},
		{
			key: "Privacy.Tracking",
			name: "[隐私] 移除响应链接跟踪参数",
			defaultValue: true,
			type: "boolean",
			description: "清理推荐、Story 与评论跳转链接中的高置信度归因参数，保留目标和界面功能参数。",
		},
		{
			key: "Privacy.BlockBiliCommercial",
			name: "[隐私] 阻止B站商业上报",
			defaultValue: false,
			type: "boolean",
			description: "本地成功响应conversion/mobile/v2与fees/wise，阻止相关请求上传。",
		},
		{
			key: "Privacy.BlockThirdParty",
			name: "[隐私] 阻止第三方广告归因",
			defaultValue: false,
			type: "boolean",
			description: "本地响应已确认的千问与Solar Engine广告展示、点击和归因请求。",
		},
		{
			key: "Privacy.Strict",
			name: "[隐私] 严格模式",
			defaultValue: false,
			type: "boolean",
			description: "同时启用响应跟踪清理、商业链接与上报阻断，并移除直播show/click callback；可能影响跳转、推荐和翻页。",
		},
		{
			key: "LogLevel",
			name: "[调试] 日志等级",
			type: "string",
			defaultValue: "WARN",
			description: "选择脚本日志的输出等级，低于所选等级的日志将全部输出。",
			options: [
				{ key: "OFF", label: "🔴 关闭" },
				{ key: "ERROR", label: "❌ 错误" },
				{ key: "WARN", label: "⚠️ 警告" },
				{ key: "INFO", label: "ℹ️ 信息" },
				{ key: "DEBUG", label: "🅱️ 调试" },
				{ key: "ALL", label: "全部" },
			],
		},
	],
});
