// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/playerunite/v1/playerunite.proto" (package "bilibili.app.playerunite.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.playerunite.v1.OpaqueMessage
 */
export interface OpaqueMessage {
}
/**
 * @generated from protobuf message bilibili.app.playerunite.v1.FragmentInfo
 */
export interface FragmentInfo {
    /**
     * @generated from protobuf field: bilibili.app.playerunite.v1.FragmentType fragment_type = 3
     */
    fragmentType: FragmentType;
}
/**
 * @generated from protobuf message bilibili.app.playerunite.v1.FragmentVideoInfo
 */
export interface FragmentVideoInfo {
    /**
     * @generated from protobuf field: bilibili.app.playerunite.v1.FragmentInfo fragment_info = 1
     */
    fragmentInfo?: FragmentInfo;
}
/**
 * @generated from protobuf message bilibili.app.playerunite.v1.FragmentVideo
 */
export interface FragmentVideo {
    /**
     * @generated from protobuf field: repeated bilibili.app.playerunite.v1.FragmentVideoInfo videos = 1
     */
    videos: FragmentVideoInfo[];
}
/**
 * @generated from protobuf message bilibili.app.playerunite.v1.ViewInfo
 */
export interface ViewInfo {
    /**
     * @generated from protobuf field: bilibili.app.playerunite.v1.OpaqueMessage prompt_bar = 2
     */
    promptBar?: OpaqueMessage;
}
/**
 * @generated from protobuf message bilibili.app.playerunite.v1.PlayViewUniteReply
 */
export interface PlayViewUniteReply {
    /**
     * @generated from protobuf field: bilibili.app.playerunite.v1.ViewInfo view_info = 9
     */
    viewInfo?: ViewInfo;
    /**
     * @generated from protobuf field: bilibili.app.playerunite.v1.FragmentVideo fragment_video = 10
     */
    fragmentVideo?: FragmentVideo;
}
/**
 * @generated from protobuf enum bilibili.app.playerunite.v1.FragmentType
 */
export declare enum FragmentType {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: AD_FRAGMENT = 1;
     */
    AD_FRAGMENT = 1,
    /**
     * @generated from protobuf enum value: OGV_FRAGMENT = 2;
     */
    OGV_FRAGMENT = 2
}
declare class OpaqueMessage$Type extends MessageType<OpaqueMessage> {
    constructor();
    create(value?: PartialMessage<OpaqueMessage>): OpaqueMessage;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OpaqueMessage): OpaqueMessage;
    internalBinaryWrite(message: OpaqueMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.OpaqueMessage
 */
export declare const OpaqueMessage: OpaqueMessage$Type;
declare class FragmentInfo$Type extends MessageType<FragmentInfo> {
    constructor();
    create(value?: PartialMessage<FragmentInfo>): FragmentInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FragmentInfo): FragmentInfo;
    internalBinaryWrite(message: FragmentInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.FragmentInfo
 */
export declare const FragmentInfo: FragmentInfo$Type;
declare class FragmentVideoInfo$Type extends MessageType<FragmentVideoInfo> {
    constructor();
    create(value?: PartialMessage<FragmentVideoInfo>): FragmentVideoInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FragmentVideoInfo): FragmentVideoInfo;
    internalBinaryWrite(message: FragmentVideoInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.FragmentVideoInfo
 */
export declare const FragmentVideoInfo: FragmentVideoInfo$Type;
declare class FragmentVideo$Type extends MessageType<FragmentVideo> {
    constructor();
    create(value?: PartialMessage<FragmentVideo>): FragmentVideo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FragmentVideo): FragmentVideo;
    internalBinaryWrite(message: FragmentVideo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.FragmentVideo
 */
export declare const FragmentVideo: FragmentVideo$Type;
declare class ViewInfo$Type extends MessageType<ViewInfo> {
    constructor();
    create(value?: PartialMessage<ViewInfo>): ViewInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewInfo): ViewInfo;
    internalBinaryWrite(message: ViewInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.ViewInfo
 */
export declare const ViewInfo: ViewInfo$Type;
declare class PlayViewUniteReply$Type extends MessageType<PlayViewUniteReply> {
    constructor();
    create(value?: PartialMessage<PlayViewUniteReply>): PlayViewUniteReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayViewUniteReply): PlayViewUniteReply;
    internalBinaryWrite(message: PlayViewUniteReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.PlayViewUniteReply
 */
export declare const PlayViewUniteReply: PlayViewUniteReply$Type;
export {};
