// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/playerunite/v1/playerunite.proto" (package "bilibili.app.playerunite.v1", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/playerunite/v1/playerunite.proto" (package "bilibili.app.playerunite.v1", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf enum bilibili.app.playerunite.v1.FragmentType
 */
export var FragmentType;
(function (FragmentType) {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    FragmentType[FragmentType["UNKNOWN"] = 0] = "UNKNOWN";
    /**
     * @generated from protobuf enum value: AD_FRAGMENT = 1;
     */
    FragmentType[FragmentType["AD_FRAGMENT"] = 1] = "AD_FRAGMENT";
    /**
     * @generated from protobuf enum value: OGV_FRAGMENT = 2;
     */
    FragmentType[FragmentType["OGV_FRAGMENT"] = 2] = "OGV_FRAGMENT";
})(FragmentType || (FragmentType = {}));
// @generated message type with reflection information, may provide speed optimized methods
class OpaqueMessage$Type extends MessageType {
    constructor() {
        super("bilibili.app.playerunite.v1.OpaqueMessage", []);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.OpaqueMessage
 */
export const OpaqueMessage = new OpaqueMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FragmentInfo$Type extends MessageType {
    constructor() {
        super("bilibili.app.playerunite.v1.FragmentInfo", [
            { no: 3, name: "fragment_type", kind: "enum", T: () => ["bilibili.app.playerunite.v1.FragmentType", FragmentType] }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.fragmentType = 0;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.app.playerunite.v1.FragmentType fragment_type */ 3:
                    message.fragmentType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.app.playerunite.v1.FragmentType fragment_type = 3; */
        if (message.fragmentType !== 0)
            writer.tag(3, WireType.Varint).int32(message.fragmentType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.FragmentInfo
 */
export const FragmentInfo = new FragmentInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FragmentVideoInfo$Type extends MessageType {
    constructor() {
        super("bilibili.app.playerunite.v1.FragmentVideoInfo", [
            { no: 1, name: "fragment_info", kind: "message", T: () => FragmentInfo }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.app.playerunite.v1.FragmentInfo fragment_info */ 1:
                    message.fragmentInfo = FragmentInfo.internalBinaryRead(reader, reader.uint32(), options, message.fragmentInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.app.playerunite.v1.FragmentInfo fragment_info = 1; */
        if (message.fragmentInfo)
            FragmentInfo.internalBinaryWrite(message.fragmentInfo, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.FragmentVideoInfo
 */
export const FragmentVideoInfo = new FragmentVideoInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FragmentVideo$Type extends MessageType {
    constructor() {
        super("bilibili.app.playerunite.v1.FragmentVideo", [
            { no: 1, name: "videos", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FragmentVideoInfo }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.videos = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bilibili.app.playerunite.v1.FragmentVideoInfo videos */ 1:
                    message.videos.push(FragmentVideoInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated bilibili.app.playerunite.v1.FragmentVideoInfo videos = 1; */
        for (let i = 0; i < message.videos.length; i++)
            FragmentVideoInfo.internalBinaryWrite(message.videos[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.FragmentVideo
 */
export const FragmentVideo = new FragmentVideo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewInfo$Type extends MessageType {
    constructor() {
        super("bilibili.app.playerunite.v1.ViewInfo", [
            { no: 2, name: "prompt_bar", kind: "message", T: () => OpaqueMessage }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.app.playerunite.v1.OpaqueMessage prompt_bar */ 2:
                    message.promptBar = OpaqueMessage.internalBinaryRead(reader, reader.uint32(), options, message.promptBar);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.app.playerunite.v1.OpaqueMessage prompt_bar = 2; */
        if (message.promptBar)
            OpaqueMessage.internalBinaryWrite(message.promptBar, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.ViewInfo
 */
export const ViewInfo = new ViewInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PlayViewUniteReply$Type extends MessageType {
    constructor() {
        super("bilibili.app.playerunite.v1.PlayViewUniteReply", [
            { no: 9, name: "view_info", kind: "message", T: () => ViewInfo },
            { no: 10, name: "fragment_video", kind: "message", T: () => FragmentVideo }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.app.playerunite.v1.ViewInfo view_info */ 9:
                    message.viewInfo = ViewInfo.internalBinaryRead(reader, reader.uint32(), options, message.viewInfo);
                    break;
                case /* bilibili.app.playerunite.v1.FragmentVideo fragment_video */ 10:
                    message.fragmentVideo = FragmentVideo.internalBinaryRead(reader, reader.uint32(), options, message.fragmentVideo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.app.playerunite.v1.ViewInfo view_info = 9; */
        if (message.viewInfo)
            ViewInfo.internalBinaryWrite(message.viewInfo, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.app.playerunite.v1.FragmentVideo fragment_video = 10; */
        if (message.fragmentVideo)
            FragmentVideo.internalBinaryWrite(message.fragmentVideo, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.PlayViewUniteReply
 */
export const PlayViewUniteReply = new PlayViewUniteReply$Type();
