// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/dynamic/v2/dynamic.proto" (package "bilibili.app.dynamic.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.dynamic.v2.DynamicItem
 */
export interface DynamicItem {
    /**
     * @generated from protobuf field: int32 card_type = 1
     */
    cardType: number;
}
/**
 * @generated from protobuf message bilibili.app.dynamic.v2.CardVideoDynList
 */
export interface CardVideoDynList {
    /**
     * @generated from protobuf field: repeated bilibili.app.dynamic.v2.DynamicItem list = 1
     */
    list: DynamicItem[];
}
/**
 * @generated from protobuf message bilibili.app.dynamic.v2.CardVideoUpList
 */
export interface CardVideoUpList {
}
/**
 * @generated from protobuf message bilibili.app.dynamic.v2.DynVideoReply
 */
export interface DynVideoReply {
    /**
     * @generated from protobuf field: bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1
     */
    dynamicList?: CardVideoDynList;
    /**
     * @generated from protobuf field: bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2
     */
    videoUpList?: CardVideoUpList;
}
declare class DynamicItem$Type extends MessageType<DynamicItem> {
    constructor();
    create(value?: PartialMessage<DynamicItem>): DynamicItem;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DynamicItem): DynamicItem;
    internalBinaryWrite(message: DynamicItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.dynamic.v2.DynamicItem
 */
export declare const DynamicItem: DynamicItem$Type;
declare class CardVideoDynList$Type extends MessageType<CardVideoDynList> {
    constructor();
    create(value?: PartialMessage<CardVideoDynList>): CardVideoDynList;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CardVideoDynList): CardVideoDynList;
    internalBinaryWrite(message: CardVideoDynList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.dynamic.v2.CardVideoDynList
 */
export declare const CardVideoDynList: CardVideoDynList$Type;
declare class CardVideoUpList$Type extends MessageType<CardVideoUpList> {
    constructor();
    create(value?: PartialMessage<CardVideoUpList>): CardVideoUpList;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CardVideoUpList): CardVideoUpList;
    internalBinaryWrite(message: CardVideoUpList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.dynamic.v2.CardVideoUpList
 */
export declare const CardVideoUpList: CardVideoUpList$Type;
declare class DynVideoReply$Type extends MessageType<DynVideoReply> {
    constructor();
    create(value?: PartialMessage<DynVideoReply>): DynVideoReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DynVideoReply): DynVideoReply;
    internalBinaryWrite(message: DynVideoReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.dynamic.v2.DynVideoReply
 */
export declare const DynVideoReply: DynVideoReply$Type;
export {};
