// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/view/v1/view.proto" (package "bilibili.app.view.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.view.v1.CM
 */
export interface CM {
}
/**
 * @generated from protobuf message bilibili.app.view.v1.CMConfig
 */
export interface CMConfig {
}
/**
 * @generated from protobuf message bilibili.app.view.v1.CmIpad
 */
export interface CmIpad {
}
/**
 * @generated from protobuf message bilibili.app.view.v1.OpaqueMessage
 */
export interface OpaqueMessage {
}
/**
 * @generated from protobuf message bilibili.app.view.v1.TIcon
 */
export interface TIcon {
    /**
     * @generated from protobuf field: string icon = 1
     */
    icon: string;
}
/**
 * @generated from protobuf message bilibili.app.view.v1.Tab
 */
export interface Tab {
    /**
     * @generated from protobuf field: int32 otype = 2
     */
    otype: number;
    /**
     * @generated from protobuf field: bilibili.app.view.v1.OpaqueMessage ad_tab_info = 11
     */
    adTabInfo?: OpaqueMessage;
}
/**
 * @generated from protobuf message bilibili.app.view.v1.Relate
 */
export interface Relate {
    /**
     * @generated from protobuf field: string title = 3
     */
    title: string;
    /**
     * @generated from protobuf field: string goto = 7
     */
    goto: string;
    /**
     * @generated from protobuf field: bilibili.app.view.v1.CM cm = 28
     */
    cm?: CM;
    /**
     * @generated from protobuf field: string unique_id = 32
     */
    uniqueId: string;
}
/**
 * @generated from protobuf message bilibili.app.view.v1.RelatesFeedReply
 */
export interface RelatesFeedReply {
    /**
     * @generated from protobuf field: repeated bilibili.app.view.v1.Relate list = 1
     */
    list: Relate[];
}
/**
 * @generated from protobuf message bilibili.app.view.v1.PlayerRelatesReply
 */
export interface PlayerRelatesReply {
    /**
     * @generated from protobuf field: repeated bilibili.app.view.v1.Relate list = 1
     */
    list: Relate[];
}
/**
 * @generated from protobuf message bilibili.app.view.v1.ViewProgressReply
 */
export interface ViewProgressReply {
    /**
     * @generated from protobuf field: bilibili.app.view.v1.OpaqueMessage video_guide = 1
     */
    videoGuide?: OpaqueMessage;
}
/**
 * @generated from protobuf message bilibili.app.view.v1.TFToast
 */
export interface TFToast {
}
/**
 * @generated from protobuf message bilibili.app.view.v1.TFPanelCustomized
 */
export interface TFPanelCustomized {
}
/**
 * @generated from protobuf message bilibili.app.view.v1.TFInfoReply
 */
export interface TFInfoReply {
    /**
     * @generated from protobuf field: int64 tips_id = 1
     */
    tipsId: string;
    /**
     * @generated from protobuf field: bilibili.app.view.v1.TFToast tf_toast = 2
     */
    tfToast?: TFToast;
    /**
     * @generated from protobuf field: bilibili.app.view.v1.TFPanelCustomized tf_panel_customized = 3
     */
    tfPanelCustomized?: TFPanelCustomized;
}
/**
 * @generated from protobuf message bilibili.app.view.v1.ViewReply
 */
export interface ViewReply {
    /**
     * @generated from protobuf field: map<string, bilibili.app.view.v1.TIcon> t_icon = 6
     */
    tIcon: {
        [key: string]: TIcon;
    };
    /**
     * @generated from protobuf field: repeated bilibili.app.view.v1.Relate relates = 10
     */
    relates: Relate[];
    /**
     * @generated from protobuf field: repeated bilibili.app.view.v1.CM cms = 30
     */
    cms: CM[];
    /**
     * @generated from protobuf field: bilibili.app.view.v1.CMConfig cm_config = 31
     */
    cmConfig?: CMConfig;
    /**
     * @generated from protobuf field: bilibili.app.view.v1.Tab tab = 32
     */
    tab?: Tab;
    /**
     * @generated from protobuf field: bilibili.app.view.v1.CmIpad cm_ipad = 41
     */
    cmIpad?: CmIpad;
    /**
     * @generated from protobuf field: bilibili.app.view.v1.OpaqueMessage cm_under_player = 48
     */
    cmUnderPlayer?: OpaqueMessage;
}
declare class CM$Type extends MessageType<CM> {
    constructor();
    create(value?: PartialMessage<CM>): CM;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CM): CM;
    internalBinaryWrite(message: CM, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.CM
 */
export declare const CM: CM$Type;
declare class CMConfig$Type extends MessageType<CMConfig> {
    constructor();
    create(value?: PartialMessage<CMConfig>): CMConfig;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CMConfig): CMConfig;
    internalBinaryWrite(message: CMConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.CMConfig
 */
export declare const CMConfig: CMConfig$Type;
declare class CmIpad$Type extends MessageType<CmIpad> {
    constructor();
    create(value?: PartialMessage<CmIpad>): CmIpad;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CmIpad): CmIpad;
    internalBinaryWrite(message: CmIpad, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.CmIpad
 */
export declare const CmIpad: CmIpad$Type;
declare class OpaqueMessage$Type extends MessageType<OpaqueMessage> {
    constructor();
    create(value?: PartialMessage<OpaqueMessage>): OpaqueMessage;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OpaqueMessage): OpaqueMessage;
    internalBinaryWrite(message: OpaqueMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.OpaqueMessage
 */
export declare const OpaqueMessage: OpaqueMessage$Type;
declare class TIcon$Type extends MessageType<TIcon> {
    constructor();
    create(value?: PartialMessage<TIcon>): TIcon;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TIcon): TIcon;
    internalBinaryWrite(message: TIcon, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.TIcon
 */
export declare const TIcon: TIcon$Type;
declare class Tab$Type extends MessageType<Tab> {
    constructor();
    create(value?: PartialMessage<Tab>): Tab;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Tab): Tab;
    internalBinaryWrite(message: Tab, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.Tab
 */
export declare const Tab: Tab$Type;
declare class Relate$Type extends MessageType<Relate> {
    constructor();
    create(value?: PartialMessage<Relate>): Relate;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Relate): Relate;
    internalBinaryWrite(message: Relate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.Relate
 */
export declare const Relate: Relate$Type;
declare class RelatesFeedReply$Type extends MessageType<RelatesFeedReply> {
    constructor();
    create(value?: PartialMessage<RelatesFeedReply>): RelatesFeedReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RelatesFeedReply): RelatesFeedReply;
    internalBinaryWrite(message: RelatesFeedReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.RelatesFeedReply
 */
export declare const RelatesFeedReply: RelatesFeedReply$Type;
declare class PlayerRelatesReply$Type extends MessageType<PlayerRelatesReply> {
    constructor();
    create(value?: PartialMessage<PlayerRelatesReply>): PlayerRelatesReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayerRelatesReply): PlayerRelatesReply;
    internalBinaryWrite(message: PlayerRelatesReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.PlayerRelatesReply
 */
export declare const PlayerRelatesReply: PlayerRelatesReply$Type;
declare class ViewProgressReply$Type extends MessageType<ViewProgressReply> {
    constructor();
    create(value?: PartialMessage<ViewProgressReply>): ViewProgressReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewProgressReply): ViewProgressReply;
    internalBinaryWrite(message: ViewProgressReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.ViewProgressReply
 */
export declare const ViewProgressReply: ViewProgressReply$Type;
declare class TFToast$Type extends MessageType<TFToast> {
    constructor();
    create(value?: PartialMessage<TFToast>): TFToast;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TFToast): TFToast;
    internalBinaryWrite(message: TFToast, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.TFToast
 */
export declare const TFToast: TFToast$Type;
declare class TFPanelCustomized$Type extends MessageType<TFPanelCustomized> {
    constructor();
    create(value?: PartialMessage<TFPanelCustomized>): TFPanelCustomized;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TFPanelCustomized): TFPanelCustomized;
    internalBinaryWrite(message: TFPanelCustomized, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.TFPanelCustomized
 */
export declare const TFPanelCustomized: TFPanelCustomized$Type;
declare class TFInfoReply$Type extends MessageType<TFInfoReply> {
    constructor();
    create(value?: PartialMessage<TFInfoReply>): TFInfoReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TFInfoReply): TFInfoReply;
    internalBinaryWrite(message: TFInfoReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.TFInfoReply
 */
export declare const TFInfoReply: TFInfoReply$Type;
declare class ViewReply$Type extends MessageType<ViewReply> {
    constructor();
    create(value?: PartialMessage<ViewReply>): ViewReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewReply): ViewReply;
    private binaryReadMap6;
    internalBinaryWrite(message: ViewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.ViewReply
 */
export declare const ViewReply: ViewReply$Type;
export {};
