// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/main/community/reply/v1/reply.proto" (package "bilibili.main.community.reply.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Wire-compatible subset for comment ads, commercial links and tracking data.
 *
 * @generated from protobuf message bilibili.main.community.reply.v1.Url
 */
export interface Url {
    /**
     * @generated from protobuf field: string app_url_schema = 4
     */
    appUrlSchema: string;
    /**
     * @generated from protobuf field: string click_report = 7
     */
    clickReport: string;
    /**
     * @generated from protobuf field: string exposure_report = 9
     */
    exposureReport: string;
    /**
     * @generated from protobuf field: string pc_url = 13
     */
    pcUrl: string;
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v1.Content
 */
export interface Content {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: map<string, bilibili.main.community.reply.v1.Url> url = 5
     */
    url: {
        [key: string]: Url;
    };
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v1.ReplyInfo
 */
export interface ReplyInfo {
    /**
     * @generated from protobuf field: repeated bilibili.main.community.reply.v1.ReplyInfo replies = 1
     */
    replies: ReplyInfo[];
    /**
     * @generated from protobuf field: bilibili.main.community.reply.v1.Content content = 12
     */
    content?: Content;
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v1.CM
 */
export interface CM {
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v1.SubjectTopCard
 */
export interface SubjectTopCard {
    /**
     * @generated from protobuf field: int32 type = 1
     */
    type: number;
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v1.MainListReply
 */
export interface MainListReply {
    /**
     * @generated from protobuf field: repeated bilibili.main.community.reply.v1.ReplyInfo replies = 2
     */
    replies: ReplyInfo[];
    /**
     * @generated from protobuf field: bilibili.main.community.reply.v1.ReplyInfo up_top = 4
     */
    upTop?: ReplyInfo;
    /**
     * @generated from protobuf field: bilibili.main.community.reply.v1.ReplyInfo admin_top = 5
     */
    adminTop?: ReplyInfo;
    /**
     * @generated from protobuf field: bilibili.main.community.reply.v1.ReplyInfo vote_top = 6
     */
    voteTop?: ReplyInfo;
    /**
     * @generated from protobuf field: bilibili.main.community.reply.v1.CM cm = 11
     */
    cm?: CM;
    /**
     * @generated from protobuf field: repeated bilibili.main.community.reply.v1.ReplyInfo top_replies = 14
     */
    topReplies: ReplyInfo[];
    /**
     * @generated from protobuf field: repeated bilibili.main.community.reply.v1.SubjectTopCard subject_top_cards = 28
     */
    subjectTopCards: SubjectTopCard[];
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v1.DetailListReply
 */
export interface DetailListReply {
    /**
     * @generated from protobuf field: bilibili.main.community.reply.v1.ReplyInfo root = 3
     */
    root?: ReplyInfo;
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v1.ReplyInfoReply
 */
export interface ReplyInfoReply {
    /**
     * @generated from protobuf field: bilibili.main.community.reply.v1.ReplyInfo reply = 1
     */
    reply?: ReplyInfo;
}
declare class Url$Type extends MessageType<Url> {
    constructor();
    create(value?: PartialMessage<Url>): Url;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Url): Url;
    internalBinaryWrite(message: Url, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.Url
 */
export declare const Url: Url$Type;
declare class Content$Type extends MessageType<Content> {
    constructor();
    create(value?: PartialMessage<Content>): Content;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Content): Content;
    private binaryReadMap5;
    internalBinaryWrite(message: Content, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.Content
 */
export declare const Content: Content$Type;
declare class ReplyInfo$Type extends MessageType<ReplyInfo> {
    constructor();
    create(value?: PartialMessage<ReplyInfo>): ReplyInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReplyInfo): ReplyInfo;
    internalBinaryWrite(message: ReplyInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.ReplyInfo
 */
export declare const ReplyInfo: ReplyInfo$Type;
declare class CM$Type extends MessageType<CM> {
    constructor();
    create(value?: PartialMessage<CM>): CM;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CM): CM;
    internalBinaryWrite(message: CM, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.CM
 */
export declare const CM: CM$Type;
declare class SubjectTopCard$Type extends MessageType<SubjectTopCard> {
    constructor();
    create(value?: PartialMessage<SubjectTopCard>): SubjectTopCard;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubjectTopCard): SubjectTopCard;
    internalBinaryWrite(message: SubjectTopCard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.SubjectTopCard
 */
export declare const SubjectTopCard: SubjectTopCard$Type;
declare class MainListReply$Type extends MessageType<MainListReply> {
    constructor();
    create(value?: PartialMessage<MainListReply>): MainListReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MainListReply): MainListReply;
    internalBinaryWrite(message: MainListReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.MainListReply
 */
export declare const MainListReply: MainListReply$Type;
declare class DetailListReply$Type extends MessageType<DetailListReply> {
    constructor();
    create(value?: PartialMessage<DetailListReply>): DetailListReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DetailListReply): DetailListReply;
    internalBinaryWrite(message: DetailListReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.DetailListReply
 */
export declare const DetailListReply: DetailListReply$Type;
declare class ReplyInfoReply$Type extends MessageType<ReplyInfoReply> {
    constructor();
    create(value?: PartialMessage<ReplyInfoReply>): ReplyInfoReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReplyInfoReply): ReplyInfoReply;
    internalBinaryWrite(message: ReplyInfoReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.ReplyInfoReply
 */
export declare const ReplyInfoReply: ReplyInfoReply$Type;
export {};
