// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/main/community/reply/v1/reply.proto" (package "bilibili.main.community.reply.v1", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class Url$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v1.Url", [
            { no: 4, name: "app_url_schema", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "click_report", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "exposure_report", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "pc_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.appUrlSchema = "";
        message.clickReport = "";
        message.exposureReport = "";
        message.pcUrl = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string app_url_schema */ 4:
                    message.appUrlSchema = reader.string();
                    break;
                case /* string click_report */ 7:
                    message.clickReport = reader.string();
                    break;
                case /* string exposure_report */ 9:
                    message.exposureReport = reader.string();
                    break;
                case /* string pc_url */ 13:
                    message.pcUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string app_url_schema = 4; */
        if (message.appUrlSchema !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.appUrlSchema);
        /* string click_report = 7; */
        if (message.clickReport !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.clickReport);
        /* string exposure_report = 9; */
        if (message.exposureReport !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.exposureReport);
        /* string pc_url = 13; */
        if (message.pcUrl !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.pcUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.Url
 */
export const Url = new Url$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Content$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v1.Content", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "url", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "message", T: () => Url } }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.message = "";
        message.url = {};
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* map<string, bilibili.main.community.reply.v1.Url> url */ 5:
                    this.binaryReadMap5(message.url, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    binaryReadMap5(map, reader, options) {
        let len = reader.uint32(), end = reader.pos + len, key, val;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = Url.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for bilibili.main.community.reply.v1.Content.url");
            }
        }
        map[key ?? ""] = val ?? Url.create();
    }
    internalBinaryWrite(message, writer, options) {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* map<string, bilibili.main.community.reply.v1.Url> url = 5; */
        for (let k of globalThis.Object.keys(message.url)) {
            writer.tag(5, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
            Url.internalBinaryWrite(message.url[k], writer, options);
            writer.join().join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.Content
 */
export const Content = new Content$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReplyInfo$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v1.ReplyInfo", [
            { no: 1, name: "replies", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ReplyInfo },
            { no: 12, name: "content", kind: "message", T: () => Content }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.replies = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bilibili.main.community.reply.v1.ReplyInfo replies */ 1:
                    message.replies.push(ReplyInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bilibili.main.community.reply.v1.Content content */ 12:
                    message.content = Content.internalBinaryRead(reader, reader.uint32(), options, message.content);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated bilibili.main.community.reply.v1.ReplyInfo replies = 1; */
        for (let i = 0; i < message.replies.length; i++)
            ReplyInfo.internalBinaryWrite(message.replies[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.main.community.reply.v1.Content content = 12; */
        if (message.content)
            Content.internalBinaryWrite(message.content, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.ReplyInfo
 */
export const ReplyInfo = new ReplyInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CM$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v1.CM", []);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.CM
 */
export const CM = new CM$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubjectTopCard$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v1.SubjectTopCard", [
            { no: 1, name: "type", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.type = 0;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 type */ 1:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int32 type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.SubjectTopCard
 */
export const SubjectTopCard = new SubjectTopCard$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MainListReply$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v1.MainListReply", [
            { no: 2, name: "replies", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ReplyInfo },
            { no: 4, name: "up_top", kind: "message", T: () => ReplyInfo },
            { no: 5, name: "admin_top", kind: "message", T: () => ReplyInfo },
            { no: 6, name: "vote_top", kind: "message", T: () => ReplyInfo },
            { no: 11, name: "cm", kind: "message", T: () => CM },
            { no: 14, name: "top_replies", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ReplyInfo },
            { no: 28, name: "subject_top_cards", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SubjectTopCard }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.replies = [];
        message.topReplies = [];
        message.subjectTopCards = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bilibili.main.community.reply.v1.ReplyInfo replies */ 2:
                    message.replies.push(ReplyInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bilibili.main.community.reply.v1.ReplyInfo up_top */ 4:
                    message.upTop = ReplyInfo.internalBinaryRead(reader, reader.uint32(), options, message.upTop);
                    break;
                case /* bilibili.main.community.reply.v1.ReplyInfo admin_top */ 5:
                    message.adminTop = ReplyInfo.internalBinaryRead(reader, reader.uint32(), options, message.adminTop);
                    break;
                case /* bilibili.main.community.reply.v1.ReplyInfo vote_top */ 6:
                    message.voteTop = ReplyInfo.internalBinaryRead(reader, reader.uint32(), options, message.voteTop);
                    break;
                case /* bilibili.main.community.reply.v1.CM cm */ 11:
                    message.cm = CM.internalBinaryRead(reader, reader.uint32(), options, message.cm);
                    break;
                case /* repeated bilibili.main.community.reply.v1.ReplyInfo top_replies */ 14:
                    message.topReplies.push(ReplyInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated bilibili.main.community.reply.v1.SubjectTopCard subject_top_cards */ 28:
                    message.subjectTopCards.push(SubjectTopCard.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated bilibili.main.community.reply.v1.ReplyInfo replies = 2; */
        for (let i = 0; i < message.replies.length; i++)
            ReplyInfo.internalBinaryWrite(message.replies[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.main.community.reply.v1.ReplyInfo up_top = 4; */
        if (message.upTop)
            ReplyInfo.internalBinaryWrite(message.upTop, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.main.community.reply.v1.ReplyInfo admin_top = 5; */
        if (message.adminTop)
            ReplyInfo.internalBinaryWrite(message.adminTop, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.main.community.reply.v1.ReplyInfo vote_top = 6; */
        if (message.voteTop)
            ReplyInfo.internalBinaryWrite(message.voteTop, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* bilibili.main.community.reply.v1.CM cm = 11; */
        if (message.cm)
            CM.internalBinaryWrite(message.cm, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* repeated bilibili.main.community.reply.v1.ReplyInfo top_replies = 14; */
        for (let i = 0; i < message.topReplies.length; i++)
            ReplyInfo.internalBinaryWrite(message.topReplies[i], writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* repeated bilibili.main.community.reply.v1.SubjectTopCard subject_top_cards = 28; */
        for (let i = 0; i < message.subjectTopCards.length; i++)
            SubjectTopCard.internalBinaryWrite(message.subjectTopCards[i], writer.tag(28, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.MainListReply
 */
export const MainListReply = new MainListReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DetailListReply$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v1.DetailListReply", [
            { no: 3, name: "root", kind: "message", T: () => ReplyInfo }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.main.community.reply.v1.ReplyInfo root */ 3:
                    message.root = ReplyInfo.internalBinaryRead(reader, reader.uint32(), options, message.root);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.main.community.reply.v1.ReplyInfo root = 3; */
        if (message.root)
            ReplyInfo.internalBinaryWrite(message.root, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.DetailListReply
 */
export const DetailListReply = new DetailListReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReplyInfoReply$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v1.ReplyInfoReply", [
            { no: 1, name: "reply", kind: "message", T: () => ReplyInfo }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.main.community.reply.v1.ReplyInfo reply */ 1:
                    message.reply = ReplyInfo.internalBinaryRead(reader, reader.uint32(), options, message.reply);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.main.community.reply.v1.ReplyInfo reply = 1; */
        if (message.reply)
            ReplyInfo.internalBinaryWrite(message.reply, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.ReplyInfoReply
 */
export const ReplyInfoReply = new ReplyInfoReply$Type();
