// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/main/community/reply/v2/reply.proto" (package "bilibili.main.community.reply.v2", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class FunctionButton$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v2.FunctionButton", [
            { no: 1, name: "type", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.type = 0;
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 type */ 1:
                    message.type = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int32 type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v2.FunctionButton
 */
export const FunctionButton = new FunctionButton$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FunctionButtonGroup$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v2.FunctionButtonGroup", [
            { no: 1, name: "buttons", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FunctionButton }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.buttons = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bilibili.main.community.reply.v2.FunctionButton buttons */ 1:
                    message.buttons.push(FunctionButton.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated bilibili.main.community.reply.v2.FunctionButton buttons = 1; */
        for (let i = 0; i < message.buttons.length; i++)
            FunctionButton.internalBinaryWrite(message.buttons[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v2.FunctionButtonGroup
 */
export const FunctionButtonGroup = new FunctionButtonGroup$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubjectDescriptionInputConfig$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v2.SubjectDescriptionInputConfig", [
            { no: 7, name: "func_buttons", kind: "message", T: () => FunctionButtonGroup }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.main.community.reply.v2.FunctionButtonGroup func_buttons */ 7:
                    message.funcButtons = FunctionButtonGroup.internalBinaryRead(reader, reader.uint32(), options, message.funcButtons);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.main.community.reply.v2.FunctionButtonGroup func_buttons = 7; */
        if (message.funcButtons)
            FunctionButtonGroup.internalBinaryWrite(message.funcButtons, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v2.SubjectDescriptionInputConfig
 */
export const SubjectDescriptionInputConfig = new SubjectDescriptionInputConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubjectDescriptionReply$Type extends MessageType {
    constructor() {
        super("bilibili.main.community.reply.v2.SubjectDescriptionReply", [
            { no: 2, name: "input", kind: "message", T: () => SubjectDescriptionInputConfig }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.main.community.reply.v2.SubjectDescriptionInputConfig input */ 2:
                    message.input = SubjectDescriptionInputConfig.internalBinaryRead(reader, reader.uint32(), options, message.input);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.main.community.reply.v2.SubjectDescriptionInputConfig input = 2; */
        if (message.input)
            SubjectDescriptionInputConfig.internalBinaryWrite(message.input, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v2.SubjectDescriptionReply
 */
export const SubjectDescriptionReply = new SubjectDescriptionReply$Type();
