// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/main/community/reply/v2/reply.proto" (package "bilibili.main.community.reply.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Wire-compatible subset used to remove commercial editor buttons.
 *
 * @generated from protobuf message bilibili.main.community.reply.v2.FunctionButton
 */
export interface FunctionButton {
    /**
     * @generated from protobuf field: int32 type = 1
     */
    type: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v2.FunctionButtonGroup
 */
export interface FunctionButtonGroup {
    /**
     * @generated from protobuf field: repeated bilibili.main.community.reply.v2.FunctionButton buttons = 1
     */
    buttons: FunctionButton[];
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v2.SubjectDescriptionInputConfig
 */
export interface SubjectDescriptionInputConfig {
    /**
     * @generated from protobuf field: bilibili.main.community.reply.v2.FunctionButtonGroup func_buttons = 7
     */
    funcButtons?: FunctionButtonGroup;
}
/**
 * @generated from protobuf message bilibili.main.community.reply.v2.SubjectDescriptionReply
 */
export interface SubjectDescriptionReply {
    /**
     * @generated from protobuf field: bilibili.main.community.reply.v2.SubjectDescriptionInputConfig input = 2
     */
    input?: SubjectDescriptionInputConfig;
}
declare class FunctionButton$Type extends MessageType<FunctionButton> {
    constructor();
    create(value?: PartialMessage<FunctionButton>): FunctionButton;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FunctionButton): FunctionButton;
    internalBinaryWrite(message: FunctionButton, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v2.FunctionButton
 */
export declare const FunctionButton: FunctionButton$Type;
declare class FunctionButtonGroup$Type extends MessageType<FunctionButtonGroup> {
    constructor();
    create(value?: PartialMessage<FunctionButtonGroup>): FunctionButtonGroup;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FunctionButtonGroup): FunctionButtonGroup;
    internalBinaryWrite(message: FunctionButtonGroup, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v2.FunctionButtonGroup
 */
export declare const FunctionButtonGroup: FunctionButtonGroup$Type;
declare class SubjectDescriptionInputConfig$Type extends MessageType<SubjectDescriptionInputConfig> {
    constructor();
    create(value?: PartialMessage<SubjectDescriptionInputConfig>): SubjectDescriptionInputConfig;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubjectDescriptionInputConfig): SubjectDescriptionInputConfig;
    internalBinaryWrite(message: SubjectDescriptionInputConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v2.SubjectDescriptionInputConfig
 */
export declare const SubjectDescriptionInputConfig: SubjectDescriptionInputConfig$Type;
declare class SubjectDescriptionReply$Type extends MessageType<SubjectDescriptionReply> {
    constructor();
    create(value?: PartialMessage<SubjectDescriptionReply>): SubjectDescriptionReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubjectDescriptionReply): SubjectDescriptionReply;
    internalBinaryWrite(message: SubjectDescriptionReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v2.SubjectDescriptionReply
 */
export declare const SubjectDescriptionReply: SubjectDescriptionReply$Type;
export {};
