// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/playurl/v1/playurl.proto" (package "bilibili.app.playurl.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Wire-compatible subset used to unlock background playback.
 *
 * @generated from protobuf message bilibili.app.playurl.v1.ExtraContent
 */
export interface ExtraContent {
}
/**
 * @generated from protobuf message bilibili.app.playurl.v1.ArcConf
 */
export interface ArcConf {
    /**
     * @generated from protobuf field: bool is_support = 1
     */
    isSupport: boolean;
    /**
     * @generated from protobuf field: bool disabled = 2
     */
    disabled: boolean;
    /**
     * @generated from protobuf field: bilibili.app.playurl.v1.ExtraContent extra_content = 3
     */
    extraContent?: ExtraContent;
}
/**
 * @generated from protobuf message bilibili.app.playurl.v1.PlayArcConf
 */
export interface PlayArcConf {
    /**
     * @generated from protobuf field: bilibili.app.playurl.v1.ArcConf background_play_conf = 1
     */
    backgroundPlayConf?: ArcConf;
}
/**
 * @generated from protobuf message bilibili.app.playurl.v1.PlayViewReply
 */
export interface PlayViewReply {
    /**
     * @generated from protobuf field: bilibili.app.playurl.v1.PlayArcConf play_arc = 5
     */
    playArc?: PlayArcConf;
}
declare class ExtraContent$Type extends MessageType<ExtraContent> {
    constructor();
    create(value?: PartialMessage<ExtraContent>): ExtraContent;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExtraContent): ExtraContent;
    internalBinaryWrite(message: ExtraContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playurl.v1.ExtraContent
 */
export declare const ExtraContent: ExtraContent$Type;
declare class ArcConf$Type extends MessageType<ArcConf> {
    constructor();
    create(value?: PartialMessage<ArcConf>): ArcConf;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ArcConf): ArcConf;
    internalBinaryWrite(message: ArcConf, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playurl.v1.ArcConf
 */
export declare const ArcConf: ArcConf$Type;
declare class PlayArcConf$Type extends MessageType<PlayArcConf> {
    constructor();
    create(value?: PartialMessage<PlayArcConf>): PlayArcConf;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayArcConf): PlayArcConf;
    internalBinaryWrite(message: PlayArcConf, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playurl.v1.PlayArcConf
 */
export declare const PlayArcConf: PlayArcConf$Type;
declare class PlayViewReply$Type extends MessageType<PlayViewReply> {
    constructor();
    create(value?: PartialMessage<PlayViewReply>): PlayViewReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayViewReply): PlayViewReply;
    internalBinaryWrite(message: PlayViewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playurl.v1.PlayViewReply
 */
export declare const PlayViewReply: PlayViewReply$Type;
export {};
