// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/community/service/dm/v1/dm.proto" (package "bilibili.community.service.dm.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.community.service.dm.v1.CommandDm
 */
export interface CommandDm {
}
/**
 * @generated from protobuf message bilibili.community.service.dm.v1.CommandDms
 */
export interface CommandDms {
    /**
     * @generated from protobuf field: repeated bilibili.community.service.dm.v1.CommandDm data = 1
     */
    data: CommandDm[];
}
/**
 * @generated from protobuf message bilibili.community.service.dm.v1.DmViewReply
 */
export interface DmViewReply {
    /**
     * @generated from protobuf field: repeated string activity_meta = 18
     */
    activityMeta: string[];
    /**
     * @generated from protobuf field: repeated bilibili.community.service.dm.v1.CommandDms commandDms = 22
     */
    commandDms: CommandDms[];
}
/**
 * @generated from protobuf message bilibili.community.service.dm.v1.DanmakuElem
 */
export interface DanmakuElem {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: int32 progress = 2
     */
    progress: number;
    /**
     * @generated from protobuf field: int32 mode = 3
     */
    mode: number;
    /**
     * @generated from protobuf field: int32 fontsize = 4
     */
    fontsize: number;
    /**
     * @generated from protobuf field: uint32 color = 5
     */
    color: number;
    /**
     * @generated from protobuf field: string midHash = 6
     */
    midHash: string;
    /**
     * @generated from protobuf field: string content = 7
     */
    content: string;
    /**
     * @generated from protobuf field: int64 ctime = 8
     */
    ctime: string;
    /**
     * @generated from protobuf field: int32 weight = 9
     */
    weight: number;
    /**
     * @generated from protobuf field: string action = 10
     */
    action: string;
    /**
     * @generated from protobuf field: int32 pool = 11
     */
    pool: number;
    /**
     * @generated from protobuf field: string idStr = 12
     */
    idStr: string;
    /**
     * @generated from protobuf field: int32 attr = 13
     */
    attr: number;
    /**
     * @generated from protobuf field: string animation = 22
     */
    animation: string;
    /**
     * @generated from protobuf field: bilibili.community.service.dm.v1.DmColorfulType colorful = 24
     */
    colorful: DmColorfulType;
    /**
     * @generated from protobuf field: int32 type = 25
     */
    type: number;
    /**
     * @generated from protobuf field: int64 oid = 26
     */
    oid: string;
    /**
     * @generated from protobuf field: int32 dm_from = 27
     */
    dmFrom: number;
}
/**
 * @generated from protobuf message bilibili.community.service.dm.v1.DmColorful
 */
export interface DmColorful {
    /**
     * @generated from protobuf field: bilibili.community.service.dm.v1.DmColorfulType type = 1
     */
    type: DmColorfulType;
    /**
     * @generated from protobuf field: string src = 2
     */
    src: string;
}
/**
 * @generated from protobuf message bilibili.community.service.dm.v1.DmSegMobileReply
 */
export interface DmSegMobileReply {
    /**
     * @generated from protobuf field: repeated bilibili.community.service.dm.v1.DanmakuElem elems = 1
     */
    elems: DanmakuElem[];
    /**
     * @generated from protobuf field: int32 state = 2
     */
    state: number;
    /**
     * @generated from protobuf field: repeated bilibili.community.service.dm.v1.DmColorful colorful_src = 5
     */
    colorfulSrc: DmColorful[];
}
/**
 * @generated from protobuf message bilibili.community.service.dm.v1.DmSegMobileReq
 */
export interface DmSegMobileReq {
    /**
     * @generated from protobuf field: int64 pid = 1
     */
    pid: string;
    /**
     * @generated from protobuf field: int64 oid = 2
     */
    oid: string;
    /**
     * @generated from protobuf field: int32 type = 3
     */
    type: number;
    /**
     * @generated from protobuf field: int64 segment_index = 4
     */
    segmentIndex: string;
}
/**
 * Wire-compatible subset used by the danmaku filters and Airborne feature.
 *
 * @generated from protobuf enum bilibili.community.service.dm.v1.DmColorfulType
 */
export declare enum DmColorfulType {
    /**
     * @generated from protobuf enum value: NoneType = 0;
     */
    NoneType = 0,
    /**
     * @generated from protobuf enum value: VipGradualColor = 60001;
     */
    VipGradualColor = 60001
}
declare class CommandDm$Type extends MessageType<CommandDm> {
    constructor();
    create(value?: PartialMessage<CommandDm>): CommandDm;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommandDm): CommandDm;
    internalBinaryWrite(message: CommandDm, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.CommandDm
 */
export declare const CommandDm: CommandDm$Type;
declare class CommandDms$Type extends MessageType<CommandDms> {
    constructor();
    create(value?: PartialMessage<CommandDms>): CommandDms;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommandDms): CommandDms;
    internalBinaryWrite(message: CommandDms, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.CommandDms
 */
export declare const CommandDms: CommandDms$Type;
declare class DmViewReply$Type extends MessageType<DmViewReply> {
    constructor();
    create(value?: PartialMessage<DmViewReply>): DmViewReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DmViewReply): DmViewReply;
    internalBinaryWrite(message: DmViewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DmViewReply
 */
export declare const DmViewReply: DmViewReply$Type;
declare class DanmakuElem$Type extends MessageType<DanmakuElem> {
    constructor();
    create(value?: PartialMessage<DanmakuElem>): DanmakuElem;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DanmakuElem): DanmakuElem;
    internalBinaryWrite(message: DanmakuElem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DanmakuElem
 */
export declare const DanmakuElem: DanmakuElem$Type;
declare class DmColorful$Type extends MessageType<DmColorful> {
    constructor();
    create(value?: PartialMessage<DmColorful>): DmColorful;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DmColorful): DmColorful;
    internalBinaryWrite(message: DmColorful, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DmColorful
 */
export declare const DmColorful: DmColorful$Type;
declare class DmSegMobileReply$Type extends MessageType<DmSegMobileReply> {
    constructor();
    create(value?: PartialMessage<DmSegMobileReply>): DmSegMobileReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DmSegMobileReply): DmSegMobileReply;
    internalBinaryWrite(message: DmSegMobileReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DmSegMobileReply
 */
export declare const DmSegMobileReply: DmSegMobileReply$Type;
declare class DmSegMobileReq$Type extends MessageType<DmSegMobileReq> {
    constructor();
    create(value?: PartialMessage<DmSegMobileReq>): DmSegMobileReq;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DmSegMobileReq): DmSegMobileReq;
    internalBinaryWrite(message: DmSegMobileReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DmSegMobileReq
 */
export declare const DmSegMobileReq: DmSegMobileReq$Type;
export {};
