// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/community/service/dm/v1/dm.proto" (package "bilibili.community.service.dm.v1", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/community/service/dm/v1/dm.proto" (package "bilibili.community.service.dm.v1", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Wire-compatible subset used by the danmaku filters and Airborne feature.
 *
 * @generated from protobuf enum bilibili.community.service.dm.v1.DmColorfulType
 */
export var DmColorfulType;
(function (DmColorfulType) {
    /**
     * @generated from protobuf enum value: NoneType = 0;
     */
    DmColorfulType[DmColorfulType["NoneType"] = 0] = "NoneType";
    /**
     * @generated from protobuf enum value: VipGradualColor = 60001;
     */
    DmColorfulType[DmColorfulType["VipGradualColor"] = 60001] = "VipGradualColor";
})(DmColorfulType || (DmColorfulType = {}));
// @generated message type with reflection information, may provide speed optimized methods
class CommandDm$Type extends MessageType {
    constructor() {
        super("bilibili.community.service.dm.v1.CommandDm", []);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.CommandDm
 */
export const CommandDm = new CommandDm$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CommandDms$Type extends MessageType {
    constructor() {
        super("bilibili.community.service.dm.v1.CommandDms", [
            { no: 1, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CommandDm }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bilibili.community.service.dm.v1.CommandDm data */ 1:
                    message.data.push(CommandDm.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated bilibili.community.service.dm.v1.CommandDm data = 1; */
        for (let i = 0; i < message.data.length; i++)
            CommandDm.internalBinaryWrite(message.data[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.CommandDms
 */
export const CommandDms = new CommandDms$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DmViewReply$Type extends MessageType {
    constructor() {
        super("bilibili.community.service.dm.v1.DmViewReply", [
            { no: 18, name: "activity_meta", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "commandDms", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CommandDms }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.activityMeta = [];
        message.commandDms = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string activity_meta */ 18:
                    message.activityMeta.push(reader.string());
                    break;
                case /* repeated bilibili.community.service.dm.v1.CommandDms commandDms */ 22:
                    message.commandDms.push(CommandDms.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated string activity_meta = 18; */
        for (let i = 0; i < message.activityMeta.length; i++)
            writer.tag(18, WireType.LengthDelimited).string(message.activityMeta[i]);
        /* repeated bilibili.community.service.dm.v1.CommandDms commandDms = 22; */
        for (let i = 0; i < message.commandDms.length; i++)
            CommandDms.internalBinaryWrite(message.commandDms[i], writer.tag(22, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DmViewReply
 */
export const DmViewReply = new DmViewReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DanmakuElem$Type extends MessageType {
    constructor() {
        super("bilibili.community.service.dm.v1.DanmakuElem", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "progress", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "mode", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "fontsize", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "color", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "midHash", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "ctime", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 9, name: "weight", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "action", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "pool", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "idStr", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "attr", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 22, name: "animation", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 24, name: "colorful", kind: "enum", T: () => ["bilibili.community.service.dm.v1.DmColorfulType", DmColorfulType] },
            { no: 25, name: "type", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 26, name: "oid", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 27, name: "dm_from", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.id = "0";
        message.progress = 0;
        message.mode = 0;
        message.fontsize = 0;
        message.color = 0;
        message.midHash = "";
        message.content = "";
        message.ctime = "0";
        message.weight = 0;
        message.action = "";
        message.pool = 0;
        message.idStr = "";
        message.attr = 0;
        message.animation = "";
        message.colorful = 0;
        message.type = 0;
        message.oid = "0";
        message.dmFrom = 0;
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toString();
                    break;
                case /* int32 progress */ 2:
                    message.progress = reader.int32();
                    break;
                case /* int32 mode */ 3:
                    message.mode = reader.int32();
                    break;
                case /* int32 fontsize */ 4:
                    message.fontsize = reader.int32();
                    break;
                case /* uint32 color */ 5:
                    message.color = reader.uint32();
                    break;
                case /* string midHash */ 6:
                    message.midHash = reader.string();
                    break;
                case /* string content */ 7:
                    message.content = reader.string();
                    break;
                case /* int64 ctime */ 8:
                    message.ctime = reader.int64().toString();
                    break;
                case /* int32 weight */ 9:
                    message.weight = reader.int32();
                    break;
                case /* string action */ 10:
                    message.action = reader.string();
                    break;
                case /* int32 pool */ 11:
                    message.pool = reader.int32();
                    break;
                case /* string idStr */ 12:
                    message.idStr = reader.string();
                    break;
                case /* int32 attr */ 13:
                    message.attr = reader.int32();
                    break;
                case /* string animation */ 22:
                    message.animation = reader.string();
                    break;
                case /* bilibili.community.service.dm.v1.DmColorfulType colorful */ 24:
                    message.colorful = reader.int32();
                    break;
                case /* int32 type */ 25:
                    message.type = reader.int32();
                    break;
                case /* int64 oid */ 26:
                    message.oid = reader.int64().toString();
                    break;
                case /* int32 dm_from */ 27:
                    message.dmFrom = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).int64(message.id);
        /* int32 progress = 2; */
        if (message.progress !== 0)
            writer.tag(2, WireType.Varint).int32(message.progress);
        /* int32 mode = 3; */
        if (message.mode !== 0)
            writer.tag(3, WireType.Varint).int32(message.mode);
        /* int32 fontsize = 4; */
        if (message.fontsize !== 0)
            writer.tag(4, WireType.Varint).int32(message.fontsize);
        /* uint32 color = 5; */
        if (message.color !== 0)
            writer.tag(5, WireType.Varint).uint32(message.color);
        /* string midHash = 6; */
        if (message.midHash !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.midHash);
        /* string content = 7; */
        if (message.content !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.content);
        /* int64 ctime = 8; */
        if (message.ctime !== "0")
            writer.tag(8, WireType.Varint).int64(message.ctime);
        /* int32 weight = 9; */
        if (message.weight !== 0)
            writer.tag(9, WireType.Varint).int32(message.weight);
        /* string action = 10; */
        if (message.action !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.action);
        /* int32 pool = 11; */
        if (message.pool !== 0)
            writer.tag(11, WireType.Varint).int32(message.pool);
        /* string idStr = 12; */
        if (message.idStr !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.idStr);
        /* int32 attr = 13; */
        if (message.attr !== 0)
            writer.tag(13, WireType.Varint).int32(message.attr);
        /* string animation = 22; */
        if (message.animation !== "")
            writer.tag(22, WireType.LengthDelimited).string(message.animation);
        /* bilibili.community.service.dm.v1.DmColorfulType colorful = 24; */
        if (message.colorful !== 0)
            writer.tag(24, WireType.Varint).int32(message.colorful);
        /* int32 type = 25; */
        if (message.type !== 0)
            writer.tag(25, WireType.Varint).int32(message.type);
        /* int64 oid = 26; */
        if (message.oid !== "0")
            writer.tag(26, WireType.Varint).int64(message.oid);
        /* int32 dm_from = 27; */
        if (message.dmFrom !== 0)
            writer.tag(27, WireType.Varint).int32(message.dmFrom);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DanmakuElem
 */
export const DanmakuElem = new DanmakuElem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DmColorful$Type extends MessageType {
    constructor() {
        super("bilibili.community.service.dm.v1.DmColorful", [
            { no: 1, name: "type", kind: "enum", T: () => ["bilibili.community.service.dm.v1.DmColorfulType", DmColorfulType] },
            { no: 2, name: "src", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.type = 0;
        message.src = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.community.service.dm.v1.DmColorfulType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* string src */ 2:
                    message.src = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.community.service.dm.v1.DmColorfulType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* string src = 2; */
        if (message.src !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.src);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DmColorful
 */
export const DmColorful = new DmColorful$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DmSegMobileReply$Type extends MessageType {
    constructor() {
        super("bilibili.community.service.dm.v1.DmSegMobileReply", [
            { no: 1, name: "elems", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DanmakuElem },
            { no: 2, name: "state", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "colorful_src", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DmColorful }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.elems = [];
        message.state = 0;
        message.colorfulSrc = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bilibili.community.service.dm.v1.DanmakuElem elems */ 1:
                    message.elems.push(DanmakuElem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 state */ 2:
                    message.state = reader.int32();
                    break;
                case /* repeated bilibili.community.service.dm.v1.DmColorful colorful_src */ 5:
                    message.colorfulSrc.push(DmColorful.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated bilibili.community.service.dm.v1.DanmakuElem elems = 1; */
        for (let i = 0; i < message.elems.length; i++)
            DanmakuElem.internalBinaryWrite(message.elems[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 state = 2; */
        if (message.state !== 0)
            writer.tag(2, WireType.Varint).int32(message.state);
        /* repeated bilibili.community.service.dm.v1.DmColorful colorful_src = 5; */
        for (let i = 0; i < message.colorfulSrc.length; i++)
            DmColorful.internalBinaryWrite(message.colorfulSrc[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DmSegMobileReply
 */
export const DmSegMobileReply = new DmSegMobileReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DmSegMobileReq$Type extends MessageType {
    constructor() {
        super("bilibili.community.service.dm.v1.DmSegMobileReq", [
            { no: 1, name: "pid", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "oid", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "type", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "segment_index", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.pid = "0";
        message.oid = "0";
        message.type = 0;
        message.segmentIndex = "0";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 pid */ 1:
                    message.pid = reader.int64().toString();
                    break;
                case /* int64 oid */ 2:
                    message.oid = reader.int64().toString();
                    break;
                case /* int32 type */ 3:
                    message.type = reader.int32();
                    break;
                case /* int64 segment_index */ 4:
                    message.segmentIndex = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* int64 pid = 1; */
        if (message.pid !== "0")
            writer.tag(1, WireType.Varint).int64(message.pid);
        /* int64 oid = 2; */
        if (message.oid !== "0")
            writer.tag(2, WireType.Varint).int64(message.oid);
        /* int32 type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* int64 segment_index = 4; */
        if (message.segmentIndex !== "0")
            writer.tag(4, WireType.Varint).int64(message.segmentIndex);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DmSegMobileReq
 */
export const DmSegMobileReq = new DmSegMobileReq$Type();
