name: Workers Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}
      - name: Install Node Dependencies
        uses: ./.github/actions/node-build
        with:
          package-token: ${{ secrets.PACKAGE_TOKEN }}
      - uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --minify -c wrangler.workers.jsonc
          wranglerVersion: "4.127.1"
